apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    database: jmeter
    user: ""
    password: ""
    isDefault: true
    jsonData:
      timeInterval: "5s"
    version: 1
    editable: true